name: lumin

channels:
    - anaconda

dependencies:
    - python==3.6
    - pytorch
    - pip:
        - seaborn==0.8.1
        - matplotlib>=3.0.2
        - pandas>=0.23.0
        - fastprogress>=0.1.18
        - scipy
        - numpy>=1.12
        - h5py
        - scikit-learn>=0.20.0
        - statsmodels>=0.9.0
        - sympy
        - pdpbox>=0.2.0
        - uproot
        - rfpimp>=1.3.4
