name: CI

on:
  push:
    branches:
      - main
  pull_request:
    paths:
        - '.github/workflows/linting.yml'
        - 'lumin/**'
        - 'poetry.lock'

jobs:
  linting:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10.12"
      - name: Install Dependencies
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          poetry install
      - name: black
        run: poetry run black --check .
      - name: isort
        run: poetry run isort --check .
      - name: flake8
        run: poetry run flake8 --exclude .venv .
      # - name: mypy
      #   run: ./run-mypy
